# unity-ci.yml
# Quantum-documented GitHub Actions workflow for Unity project CI
# Builds the project on push to main or PR

name: Unity CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Assets/**', '**/Packages/**', '**/ProjectSettings/**') }}
      - name: Set up Unity
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: 2022.3.0f1
      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          projectPath: .
          buildTarget: StandaloneWindows64
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build 